// 烹饪（Cooking）— 需求文档 §3.2.1（核心技能，50 个食谱）
// 将食材组合制作成料理；料理分 主食/主菜/汤品/甜点 四类；
// 料理用途（对决回血/任务交付/出售/图鉴）已接入对决与餐厅系统。
// 食谱按文档 7 档回血覆盖 L1~L99，材料全部来自当前可获取的食材/酱料/调料。

import { ProductionSkill } from './ProductionSkill.js'
import { PRODUCTION_EXT } from '../data/expansion1.js'
import { PRODUCTION_EXT2 } from '../data/expansion2.js'
import { raiseRecipeLevels } from './recipeBalance.js'

export const COOKING_RECIPES = [
  // ── 1-10 级（回血 10-30）──
  { id: 'roastPotato', name: '烤土豆', category: '主食', reqLevel: 1, xp: 30, successChance: 0.9, ingredients: { potato: 2 }, output: { itemId: 'roastPotato', qty: 1 } },
  { id: 'vegSalad', name: '蔬菜沙拉', category: '主菜', reqLevel: 3, xp: 45, successChance: 0.88, ingredients: { carrot: 1, tomato: 1, apple: 1 }, output: { itemId: 'vegSalad', qty: 1 } },
  { id: 'boiledCabbage', name: '开水白菜', category: '主菜', reqLevel: 4, xp: 52, successChance: 0.88, ingredients: { cabbage: 2, saltOre: 1 }, output: { itemId: 'boiledCabbage', qty: 1 } },
  { id: 'steamedSweetPotato', name: '蒸红薯', category: '主食', reqLevel: 6, xp: 62, successChance: 0.87, ingredients: { sweetPotato: 2 }, output: { itemId: 'steamedSweetPotato', qty: 1 } },
  { id: 'cornOnCob', name: '煮玉米', category: '主食', reqLevel: 7, xp: 68, successChance: 0.87, ingredients: { corn: 2 }, output: { itemId: 'cornOnCob', qty: 1 } },
  { id: 'steamedCrucian', name: '清蒸鲫鱼', category: '主菜', reqLevel: 8, xp: 70, successChance: 0.85, ingredients: { crucian: 2, saltOre: 1 }, output: { itemId: 'steamedCrucian', qty: 1 } },
  { id: 'fruitPlatter', name: '水果拼盘', category: '甜点', reqLevel: 9, xp: 82, successChance: 0.86, ingredients: { apple: 1, strawberry: 1, grape: 1 }, output: { itemId: 'fruitPlatter', qty: 1 } },
  { id: 'plainNoodles', name: '清汤面', category: '主食', reqLevel: 10, xp: 90, successChance: 0.85, ingredients: { flour: 1, saltOre: 1, cabbage: 1 }, output: { itemId: 'plainNoodles', qty: 1 } },
  // ── 11-25 级（回血 40-80）──
  { id: 'tomatoEgg', name: '番茄炒蛋', category: '主菜', reqLevel: 12, xp: 100, successChance: 0.85, ingredients: { tomato: 2, pheasantEgg: 1 }, output: { itemId: 'tomatoEgg', qty: 1 } },
  { id: 'eggFriedRice', name: '蛋炒饭', category: '主食', reqLevel: 13, xp: 112, successChance: 0.84, ingredients: { rice: 2, pheasantEgg: 1 }, output: { itemId: 'eggFriedRice', qty: 1 } },
  { id: 'carpSoup', name: '炖鲤鱼汤', category: '汤品', reqLevel: 15, xp: 130, successChance: 0.82, ingredients: { carp: 2, potato: 1 }, output: { itemId: 'carpSoup', qty: 1 } },
  { id: 'sweetSourCabbage', name: '醋溜白菜', category: '主菜', reqLevel: 17, xp: 145, successChance: 0.82, ingredients: { cabbage: 2, soySauce: 1, chili: 1 }, output: { itemId: 'sweetSourCabbage', qty: 1 } },
  { id: 'ironPlateRabbit', name: '铁板兔肉', category: '主菜', reqLevel: 18, xp: 158, successChance: 0.81, ingredients: { rabbitMeat: 2, onion: 1, pepperSalt: 1 }, output: { itemId: 'ironPlateRabbit', qty: 1 } },
  { id: 'wildBBQ', name: '野味烧烤', category: '主菜', reqLevel: 20, xp: 180, successChance: 0.8, ingredients: { rabbitMeat: 1, pheasantMeat: 1, chili: 1, doubanjiang: 1 }, output: { itemId: 'wildBBQ', qty: 1 } },
  { id: 'cornChowder', name: '玉米浓汤', category: '汤品', reqLevel: 22, xp: 195, successChance: 0.8, ingredients: { corn: 2, flour: 1, saltOre: 1 }, output: { itemId: 'cornChowder', qty: 1 } },
  { id: 'baconFriedRice', name: '腊肉炒饭', category: '主食', reqLevel: 22, xp: 200, successChance: 0.79, ingredients: { rice: 2, bacon: 1, pheasantEgg: 1 }, output: { itemId: 'baconFriedRice', qty: 1 } },
  { id: 'kimchiStew', name: '泡菜汤', category: '汤品', reqLevel: 24, xp: 218, successChance: 0.79, ingredients: { kimchi: 2, boarMeat: 1 }, output: { itemId: 'kimchiStew', qty: 1 } },
  // ── 26-40 级（回血 90-150）──
  { id: 'braisedPheasant', name: '黄焖野鸡', category: '主菜', reqLevel: 26, xp: 250, successChance: 0.78, ingredients: { pheasantMeat: 2, potato: 2, soySauce: 1 }, output: { itemId: 'braisedPheasant', qty: 1 } },
  { id: 'braisedPerch', name: '红烧鲈鱼', category: '主菜', reqLevel: 28, xp: 260, successChance: 0.78, ingredients: { perch: 2, onion: 1, ginger: 1, soySauce: 1 }, output: { itemId: 'braisedPerch', qty: 1 } },
  { id: 'yuxiangPork', name: '鱼香肉丝', category: '主菜', reqLevel: 30, xp: 300, successChance: 0.77, ingredients: { boarMeat: 1, doubanjiang: 1, garlic: 1, carrot: 1 }, output: { itemId: 'yuxiangPork', qty: 1 } },
  { id: 'braisedEggplant', name: '酱爆茄子', category: '主菜', reqLevel: 32, xp: 330, successChance: 0.76, ingredients: { eggplant: 3, doubanjiang: 1, garlic: 1 }, output: { itemId: 'braisedEggplant', qty: 1 } },
  { id: 'venisonSteak', name: '香煎鹿排', category: '主菜', reqLevel: 34, xp: 355, successChance: 0.76, ingredients: { venison: 2, rosemary: 1, saltOre: 1 }, output: { itemId: 'venisonSteak', qty: 1 } },
  { id: 'seafoodStew', name: '海鲜大杂烩', category: '汤品', reqLevel: 35, xp: 340, successChance: 0.75, ingredients: { salmon: 1, tuna: 1, eel: 1, saltOre: 1, fishSauce: 1 }, output: { itemId: 'seafoodStew', qty: 1 } },
  { id: 'boiledFish', name: '水煮鱼', category: '主菜', reqLevel: 37, xp: 400, successChance: 0.74, ingredients: { perch: 2, chili: 2, doubanjiang: 1, garlic: 1 }, output: { itemId: 'boiledFish', qty: 1 } },
  { id: 'curryPheasant', name: '咖喱野鸡', category: '主菜', reqLevel: 39, xp: 430, successChance: 0.73, ingredients: { pheasantMeat: 2, curryPowder: 1, potato: 1 }, output: { itemId: 'curryPheasant', qty: 1 } },
  // ── 41-55 级（回血 160-250）──
  { id: 'garlicLobster', name: '蒜香龙虾', category: '主菜', reqLevel: 45, xp: 470, successChance: 0.72, ingredients: { lobster: 2, garlic: 2, garlicPaste: 1 }, output: { itemId: 'garlicLobster', qty: 1 } },
  { id: 'eelKabayaki', name: '蒲烧鳗鱼', category: '主菜', reqLevel: 46, xp: 510, successChance: 0.71, ingredients: { eel: 2, soySauce: 1, peppercorn: 1 }, output: { itemId: 'eelKabayaki', qty: 1 } },
  { id: 'sushiPlatter', name: '寿司拼盘', category: '主菜', reqLevel: 48, xp: 540, successChance: 0.71, ingredients: { rice: 2, salmon: 1, tuna: 1, saltOre: 1 }, output: { itemId: 'sushiPlatter', qty: 1 } },
  { id: 'lobsterCongee', name: '龙虾粥', category: '汤品', reqLevel: 50, xp: 570, successChance: 0.7, ingredients: { lobster: 1, rice: 2, ginger: 1 }, output: { itemId: 'lobsterCongee', qty: 1 } },
  { id: 'pepperSaltLobster', name: '椒盐龙虾', category: '主菜', reqLevel: 52, xp: 600, successChance: 0.7, ingredients: { lobster: 2, pepperSalt: 1 }, output: { itemId: 'pepperSaltLobster', qty: 1 } },
  { id: 'goatHotpot', name: '山珍羊肉炉', category: '汤品', reqLevel: 54, xp: 640, successChance: 0.69, ingredients: { goatMeat: 2, yam: 1, ginger: 1, starAnise: 1 }, output: { itemId: 'goatHotpot', qty: 1 } },
  { id: 'herbCrab', name: '香草烤蟹', category: '主菜', reqLevel: 55, xp: 620, successChance: 0.7, ingredients: { crab: 2, vanilla: 1, herbSalt: 1 }, output: { itemId: 'herbCrab', qty: 1 } },
  { id: 'buddhaJump', name: '佛跳墙（简化版）', category: '汤品', reqLevel: 55, xp: 670, successChance: 0.68, ingredients: { abalone: 1, seaCucumber: 1, lobster: 1, matsutake: 1, soySauce: 1 }, output: { itemId: 'buddhaJump', qty: 1 } },
  // ── 56-70 级（回血 260-400）──
  { id: 'lobsterSashimi', name: '龙虾刺身', category: '主菜', reqLevel: 58, xp: 710, successChance: 0.68, ingredients: { lobster: 2, ginger: 1, soySauce: 1 }, output: { itemId: 'lobsterSashimi', qty: 1 } },
  { id: 'bluefinSashimi', name: '蓝鳍刺身', category: '主菜', reqLevel: 60, xp: 750, successChance: 0.67, ingredients: { bluefin: 1, ginger: 1, soySauce: 1 }, output: { itemId: 'bluefinSashimi', qty: 1 } },
  { id: 'trufflePasta', name: '松露意面', category: '主食', reqLevel: 62, xp: 790, successChance: 0.67, ingredients: { flour: 2, truffle: 1, vanilla: 1, saltOre: 1 }, output: { itemId: 'trufflePasta', qty: 1 } },
  { id: 'lingzhiStew', name: '灵芝炖品', category: '汤品', reqLevel: 64, xp: 830, successChance: 0.66, ingredients: { lingzhi: 1, yam: 2, saltOre: 1 }, output: { itemId: 'lingzhiStew', qty: 1 } },
  { id: 'abaloneStew', name: '鲍鱼炖品', category: '汤品', reqLevel: 65, xp: 800, successChance: 0.68, ingredients: { abalone: 2, lingzhi: 1, ginseng: 1, saffronPowder: 1 }, output: { itemId: 'abaloneStew', qty: 1 } },
  { id: 'ginsengPheasant', name: '人参炖山鸡', category: '汤品', reqLevel: 66, xp: 870, successChance: 0.66, ingredients: { pheasantMeat: 2, ginseng: 1, ginger: 1 }, output: { itemId: 'ginsengPheasant', qty: 1 } },
  { id: 'seaCucumberStew', name: '葱烧海参', category: '主菜', reqLevel: 68, xp: 910, successChance: 0.65, ingredients: { seaCucumber: 2, onion: 1, soySauce: 1 }, output: { itemId: 'seaCucumberStew', qty: 1 } },
  { id: 'manhanSingle', name: '满汉全席（单品）', category: '主菜', reqLevel: 70, xp: 970, successChance: 0.65, ingredients: { matsutake: 1, abalone: 1, ginseng: 1, fishSauce: 1 }, output: { itemId: 'manhanSingle', qty: 1 } },
  // ── 71-85 级（回血 410-600）──
  { id: 'braisedBearPaw', name: '红烧熊掌', category: '主菜', reqLevel: 72, xp: 1040, successChance: 0.64, ingredients: { bearMeat: 1, soySauce: 2, garlic: 1 }, output: { itemId: 'braisedBearPaw', qty: 1 } },
  { id: 'grouperFeast', name: '龙趸盛宴', category: '主菜', reqLevel: 75, xp: 1050, successChance: 0.65, ingredients: { grouper: 1, matsutake: 1, saffron: 1, fiveSpice: 1 }, output: { itemId: 'grouperFeast', qty: 1 } },
  { id: 'mammothRoast', name: '猛犸象烤肉', category: '主菜', reqLevel: 78, xp: 1170, successChance: 0.62, ingredients: { mammothMeat: 1, bbqPowder: 1, rosemary: 1 }, output: { itemId: 'mammothRoast', qty: 1 } },
  { id: 'dragonHotpot', name: '龙息火锅', category: '汤品', reqLevel: 80, xp: 1240, successChance: 0.61, ingredients: { dragonPepper: 2, crocodileMeat: 1, chili: 1, saltOre: 1 }, output: { itemId: 'dragonHotpot', qty: 1 } },
  { id: 'goldenFeast', name: '金龙鱼全宴', category: '主菜', reqLevel: 85, xp: 1400, successChance: 0.6, ingredients: { goldenDragonFish: 1, truffle: 2, dragonRoot: 1, dragonSalt: 1 }, output: { itemId: 'goldenFeast', qty: 1 } },
  // ── 86-99 级（回血 610-1000，传说）──
  { id: 'chefFriedRice', name: '食神炒饭', category: '主食', reqLevel: 88, xp: 1500, successChance: 0.58, ingredients: { rice: 2, spiritFruit: 1, truffle: 1, dragonPepper: 1 }, output: { itemId: 'chefFriedRice', qty: 1 } },
  { id: 'legendaryManHan', name: '传说满汉全席', category: '主菜', reqLevel: 90, xp: 1680, successChance: 0.56, ingredients: { matsutake: 2, abalone: 2, seaCucumber: 1, lingzhi: 1 }, output: { itemId: 'legendaryManHan', qty: 1 } },
  { id: 'dragonRoast', name: '龙息烤全龙', category: '主菜', reqLevel: 95, xp: 1980, successChance: 0.52, ingredients: { dragonMeat: 1, dragonSalt: 1, truffle: 2 }, output: { itemId: 'dragonRoast', qty: 1 } },
  { id: 'godFeast', name: '食神盛宴', category: '主菜', reqLevel: 99, xp: 2400, successChance: 0.5, ingredients: { goldenDragonFish: 1, dragonMeat: 1, spiritFruit: 2, truffle: 2 }, output: { itemId: 'godFeast', qty: 1 } },
  // ── 批量场景B：蔬菜/根茎/菌类菜品（消耗未被配方的采集材料）──
  { id: 'radishSoup', name: '萝卜汤', category: '汤品', reqLevel: 3, xp: 30, successChance: 0.9, ingredients: { excavation_ext_01: 3, saltOre: 1 }, output: { itemId: 'radishSoup', qty: 1 } },
  { id: 'greenRadishSalad', name: '凉拌青萝卜', category: '主菜', reqLevel: 6, xp: 50, successChance: 0.89, ingredients: { excavation_ext_02: 2, soySauce: 1, garlic: 1 }, output: { itemId: 'greenRadishSalad', qty: 1 } },
  { id: 'beetSalad', name: '甜菜沙拉', category: '主菜', reqLevel: 13, xp: 90, successChance: 0.88, ingredients: { excavation_ext_04: 2, saltOre: 1 }, output: { itemId: 'beetSalad', qty: 1 } },
  { id: 'waterChestnutStir', name: '清炒荸荠', category: '主菜', reqLevel: 16, xp: 108, successChance: 0.87, ingredients: { excavation_ext_05: 2, soySauce: 1, garlic: 1 }, output: { itemId: 'waterChestnutStir', qty: 1 } },
  { id: 'arrowheadSoup', name: '慈姑汤', category: '汤品', reqLevel: 19, xp: 128, successChance: 0.86, ingredients: { excavation_ext_06: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'arrowheadSoup', qty: 1 } },
  { id: 'lotusRootSoup', name: '莲藕汤', category: '汤品', reqLevel: 22, xp: 145, successChance: 0.86, ingredients: { excavation_ext_07: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'lotusRootSoup', qty: 1 } },
  { id: 'poriaPorridge', name: '茯苓粥', category: '主食', reqLevel: 40, xp: 260, successChance: 0.82, ingredients: { excavation_ext_12: 2, rice: 2 }, output: { itemId: 'poriaPorridge', qty: 1 } },
  { id: 'taroBraised', name: '红烧芋头', category: '主菜', reqLevel: 30, xp: 205, successChance: 0.84, ingredients: { excavation_ext_09: 2, soySauce: 2, garlic: 1 }, output: { itemId: 'taroBraised', qty: 1 } },
  { id: 'tapiocaStew', name: '木薯炖肉', category: '主菜', reqLevel: 32, xp: 215, successChance: 0.83, ingredients: { excavation_ext_10: 2, bacon: 1, soySauce: 1 }, output: { itemId: 'tapiocaStew', qty: 1 } },
  { id: 'kudzuSoup', name: '葛根汤', category: '汤品', reqLevel: 36, xp: 240, successChance: 0.82, ingredients: { excavation_ext_11: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'kudzuSoup', qty: 1 } },
  { id: 'braisedPeanut', name: '卤煮花生', category: '主菜', reqLevel: 70, xp: 940, successChance: 0.66, ingredients: { foraging_ext_21: 3, fiveSpice: 1, saltOre: 1 }, output: { itemId: 'braisedPeanut', qty: 1 } },
  { id: 'fungusStir', name: '木耳炒肉', category: '主菜', reqLevel: 72, xp: 985, successChance: 0.65, ingredients: { foraging_ext_22: 2, bacon: 1, garlic: 1 }, output: { itemId: 'fungusStir', qty: 1 } },
  { id: 'silverFungusSoup', name: '银耳羹', category: '汤品', reqLevel: 76, xp: 1060, successChance: 0.64, ingredients: { foraging_ext_23: 2, ginger: 1 }, output: { itemId: 'silverFungusSoup', qty: 1 } },
  { id: 'braisedBamboo', name: '油焖竹笋', category: '主菜', reqLevel: 80, xp: 1180, successChance: 0.62, ingredients: { foraging_ext_24: 2, soySauce: 2, saltOre: 1 }, output: { itemId: 'braisedBamboo', qty: 1 } },
  { id: 'asparagusStir', name: '清炒芦笋', category: '主菜', reqLevel: 84, xp: 1290, successChance: 0.6, ingredients: { foraging_ext_25: 2, garlic: 1, saltOre: 1 }, output: { itemId: 'asparagusStir', qty: 1 } },
  { id: 'spinachSoup', name: '菠菜汤', category: '汤品', reqLevel: 86, xp: 1360, successChance: 0.6, ingredients: { foraging_ext_26: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'spinachSoup', qty: 1 } },
  { id: 'celeryStir', name: '芹菜炒肉', category: '主菜', reqLevel: 89, xp: 1450, successChance: 0.59, ingredients: { foraging_ext_27: 2, bacon: 1, saltOre: 1 }, output: { itemId: 'celeryStir', qty: 1 } },
  // ── 批量场景B：海鲜类菜品（消耗未被配方的采集鱼/贝）──
  { id: 'codSteak', name: '香煎鳕鱼', category: '主菜', reqLevel: 9, xp: 70, successChance: 0.89, ingredients: { fishing_ext_03: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'codSteak', qty: 1 } },
  { id: 'whitebaitStir', name: '银鱼炒蛋', category: '主菜', reqLevel: 9, xp: 72, successChance: 0.89, ingredients: { fishing_ext2_03: 2, pheasantEgg: 1, saltOre: 1 }, output: { itemId: 'whitebaitStir', qty: 1 } },
  { id: 'flounderSteam', name: '清蒸比目鱼', category: '主菜', reqLevel: 13, xp: 95, successChance: 0.88, ingredients: { fishing_ext_04: 2, ginger: 1, soySauce: 1 }, output: { itemId: 'flounderSteam', qty: 1 } },
  { id: 'grouperSteam', name: '清蒸石斑', category: '主菜', reqLevel: 16, xp: 108, successChance: 0.87, ingredients: { fishing_ext_05: 2, ginger: 1, soySauce: 1 }, output: { itemId: 'grouperSteam', qty: 1 } },
  { id: 'turbotSoup', name: '多宝鱼汤', category: '汤品', reqLevel: 19, xp: 128, successChance: 0.86, ingredients: { fishing_ext_06: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'turbotSoup', qty: 1 } },
  { id: 'anchoviesFry', name: '香酥凤尾鱼', category: '主菜', reqLevel: 13, xp: 95, successChance: 0.88, ingredients: { fishing_ext2_04: 2, saltOre: 1, chili: 1 }, output: { itemId: 'anchoviesFry', qty: 1 } },
  { id: 'rainbowTroutRoast', name: '烤虹鳟', category: '主菜', reqLevel: 16, xp: 108, successChance: 0.87, ingredients: { fishing_ext2_05: 2, chili: 1, saltOre: 1 }, output: { itemId: 'rainbowTroutRoast', qty: 1 } },
  { id: 'ayuGrill', name: '盐烤香鱼', category: '主菜', reqLevel: 19, xp: 128, successChance: 0.86, ingredients: { fishing_ext2_06: 2, saltOre: 1 }, output: { itemId: 'ayuGrill', qty: 1 } },
  { id: 'sauryGrill', name: '盐烤秋刀鱼', category: '主菜', reqLevel: 23, xp: 152, successChance: 0.86, ingredients: { fishing_ext_07: 2, saltOre: 1 }, output: { itemId: 'sauryGrill', qty: 1 } },
  { id: 'sturgeonSteam', name: '清蒸鲟鱼', category: '主菜', reqLevel: 23, xp: 152, successChance: 0.86, ingredients: { fishing_ext2_07: 2, ginger: 1, soySauce: 1 }, output: { itemId: 'sturgeonSteam', qty: 1 } },
  { id: 'swordfishSteak', name: '香煎旗鱼', category: '主菜', reqLevel: 26, xp: 172, successChance: 0.85, ingredients: { fishing_ext_08: 2, soySauce: 1, ginger: 1 }, output: { itemId: 'swordfishSteak', qty: 1 } },
  { id: 'marlinSteak', name: '剑鱼排', category: '主菜', reqLevel: 30, xp: 200, successChance: 0.84, ingredients: { fishing_ext_09: 2, soySauce: 1, garlic: 1 }, output: { itemId: 'marlinSteak', qty: 1 } },
  { id: 'oysterGarlic', name: '蒜蓉烤牡蛎', category: '主菜', reqLevel: 53, xp: 380, successChance: 0.78, ingredients: { fishing_ext_16: 2, garlic: 2, chili: 1 }, output: { itemId: 'oysterGarlic', qty: 1 } },
  { id: 'scallopGarlic', name: '蒜蓉蒸扇贝', category: '主菜', reqLevel: 57, xp: 425, successChance: 0.77, ingredients: { fishing_ext_17: 2, garlic: 2, saltOre: 1 }, output: { itemId: 'scallopGarlic', qty: 1 } },
  { id: 'clamSoup', name: '蛤蜊汤', category: '汤品', reqLevel: 60, xp: 455, successChance: 0.76, ingredients: { fishing_ext_18: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'clamSoup', qty: 1 } },
  // ── 批量场景B：海鲜贝/螺/虾蟹/鱼（第二批）──
  { id: 'silverCarpBraised', name: '红烧白鲢', category: '主菜', reqLevel: 26, xp: 175, successChance: 0.85, ingredients: { fishing_ext2_08: 2, soySauce: 1, ginger: 1 }, output: { itemId: 'silverCarpBraised', qty: 1 } },
  { id: 'fishHeadSteam', name: '剁椒鱼头', category: '主菜', reqLevel: 30, xp: 200, successChance: 0.84, ingredients: { fishing_ext2_09: 2, chili: 2, ginger: 1 }, output: { itemId: 'fishHeadSteam', qty: 1 } },
  { id: 'yellowCroakerBraised', name: '红烧黄花鱼', category: '主菜', reqLevel: 33, xp: 220, successChance: 0.83, ingredients: { fishing_ext_10: 2, soySauce: 1, ginger: 1 }, output: { itemId: 'yellowCroakerBraised', qty: 1 } },
  { id: 'hairtailFry', name: '香煎带鱼', category: '主菜', reqLevel: 36, xp: 240, successChance: 0.82, ingredients: { fishing_ext_11: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'hairtailFry', qty: 1 } },
  { id: 'pomfretSteam', name: '清蒸鲳鱼', category: '主菜', reqLevel: 40, xp: 268, successChance: 0.81, ingredients: { fishing_ext_12: 2, ginger: 1, soySauce: 1 }, output: { itemId: 'pomfretSteam', qty: 1 } },
  { id: 'blackCarpBraised', name: '红烧青鱼', category: '主菜', reqLevel: 33, xp: 220, successChance: 0.83, ingredients: { fishing_ext2_10: 2, soySauce: 1, ginger: 1 }, output: { itemId: 'blackCarpBraised', qty: 1 } },
  { id: 'grassCarpBoiled', name: '水煮草鱼', category: '主菜', reqLevel: 36, xp: 240, successChance: 0.82, ingredients: { fishing_ext2_11: 2, chili: 2, garlic: 1 }, output: { itemId: 'grassCarpBoiled', qty: 1 } },
  { id: 'squidStir', name: '爆炒鱿鱼', category: '主菜', reqLevel: 43, xp: 295, successChance: 0.8, ingredients: { fishing_ext_13: 2, chili: 1, garlic: 1 }, output: { itemId: 'squidStir', qty: 1 } },
  { id: 'octopusGarlic', name: '蒜香章鱼', category: '主菜', reqLevel: 46, xp: 320, successChance: 0.79, ingredients: { fishing_ext_14: 2, garlic: 2, saltOre: 1 }, output: { itemId: 'octopusGarlic', qty: 1 } },
  { id: 'cuttlefishSoup', name: '墨鱼炖汤', category: '汤品', reqLevel: 50, xp: 350, successChance: 0.78, ingredients: { fishing_ext_15: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'cuttlefishSoup', qty: 1 } },
  { id: 'razorClamOil', name: '葱油蛏子', category: '主菜', reqLevel: 63, xp: 500, successChance: 0.75, ingredients: { fishing_ext_19: 2, saltOre: 1, garlic: 1 }, output: { itemId: 'razorClamOil', qty: 1 } },
  { id: 'seaUrchinEgg', name: '蒸蛋海胆', category: '主菜', reqLevel: 67, xp: 550, successChance: 0.74, ingredients: { fishing_ext_20: 2, pheasantEgg: 2, saltOre: 1 }, output: { itemId: 'seaUrchinEgg', qty: 1 } },
  { id: 'conchSauce', name: '酱爆海螺', category: '主菜', reqLevel: 70, xp: 590, successChance: 0.73, ingredients: { fishing_ext_21: 2, soySauce: 2, chili: 1 }, output: { itemId: 'conchSauce', qty: 1 } },
  { id: 'prawnBoiled', name: '白灼对虾', category: '主菜', reqLevel: 77, xp: 680, successChance: 0.7, ingredients: { fishing_ext_23: 3, ginger: 1, saltOre: 1 }, output: { itemId: 'prawnBoiled', qty: 1 } },
  { id: 'mantisShrimpSalt', name: '椒盐皮皮虾', category: '主菜', reqLevel: 80, xp: 730, successChance: 0.69, ingredients: { fishing_ext_24: 3, saltOre: 1, fiveSpice: 1 }, output: { itemId: 'mantisShrimpSalt', qty: 1 } },
  // ── 批量场景B：海鲜鲍/藻/贝/虾蟹（第三批）──
  { id: 'tilapiaBraised', name: '红烧罗非鱼', category: '主菜', reqLevel: 40, xp: 270, successChance: 0.81, ingredients: { fishing_ext2_12: 2, soySauce: 1, ginger: 1 }, output: { itemId: 'tilapiaBraised', qty: 1 } },
  { id: 'bassaFry', name: '香煎巴沙鱼', category: '主菜', reqLevel: 43, xp: 295, successChance: 0.8, ingredients: { fishing_ext2_13: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'bassaFry', qty: 1 } },
  { id: 'wuchangSteam', name: '清蒸武昌鱼', category: '主菜', reqLevel: 46, xp: 320, successChance: 0.79, ingredients: { fishing_ext2_14: 2, ginger: 1, soySauce: 1 }, output: { itemId: 'wuchangSteam', qty: 1 } },
  { id: 'agarSalad', name: '凉拌石花菜', category: '主菜', reqLevel: 50, xp: 355, successChance: 0.78, ingredients: { fishing_ext2_15: 2, saltOre: 1, garlic: 1 }, output: { itemId: 'agarSalad', qty: 1 } },
  { id: 'asparagusSeaStir', name: '清炒龙须菜', category: '主菜', reqLevel: 53, xp: 385, successChance: 0.77, ingredients: { fishing_ext2_16: 2, garlic: 1, saltOre: 1 }, output: { itemId: 'asparagusSeaStir', qty: 1 } },
  { id: 'wakameSoup', name: '裙带菜汤', category: '汤品', reqLevel: 57, xp: 425, successChance: 0.76, ingredients: { fishing_ext2_17: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'wakameSoup', qty: 1 } },
  { id: 'kelpSoup', name: '海带汤', category: '汤品', reqLevel: 60, xp: 455, successChance: 0.76, ingredients: { fishing_ext2_18: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'kelpSoup', qty: 1 } },
  { id: 'laverSoup', name: '紫菜蛋汤', category: '汤品', reqLevel: 63, xp: 500, successChance: 0.75, ingredients: { fishing_ext2_19: 2, pheasantEgg: 2, saltOre: 1 }, output: { itemId: 'laverSoup', qty: 1 } },
  { id: 'musselSoup', name: '淡菜汤', category: '汤品', reqLevel: 67, xp: 550, successChance: 0.74, ingredients: { fishing_ext2_20: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'musselSoup', qty: 1 } },
  { id: 'akagaiStir', name: '辣炒赤贝', category: '主菜', reqLevel: 70, xp: 590, successChance: 0.73, ingredients: { fishing_ext2_21: 2, chili: 2, garlic: 1 }, output: { itemId: 'akagaiStir', qty: 1 } },
  { id: 'musselGarlic', name: '蒜蓉贻贝', category: '主菜', reqLevel: 73, xp: 630, successChance: 0.72, ingredients: { fishing_ext_22: 2, garlic: 2, saltOre: 1 }, output: { itemId: 'musselGarlic', qty: 1 } },
  { id: 'birdClamBoiled', name: '白灼鸟贝', category: '主菜', reqLevel: 73, xp: 635, successChance: 0.72, ingredients: { fishing_ext2_22: 3, ginger: 1, saltOre: 1 }, output: { itemId: 'birdClamBoiled', qty: 1 } },
  { id: 'bloodClamSalad', name: '凉拌血蛤', category: '主菜', reqLevel: 77, xp: 690, successChance: 0.7, ingredients: { fishing_ext2_23: 3, garlic: 1, soySauce: 1 }, output: { itemId: 'bloodClamSalad', qty: 1 } },
  { id: 'arkShellGinger', name: '姜葱毛蚶', category: '主菜', reqLevel: 80, xp: 730, successChance: 0.69, ingredients: { fishing_ext2_24: 3, ginger: 2, saltOre: 1 }, output: { itemId: 'arkShellGinger', qty: 1 } },
  { id: 'braisedPrawn', name: '油焖大虾', category: '主菜', reqLevel: 84, xp: 810, successChance: 0.67, ingredients: { fishing_ext_25: 3, soySauce: 2, ginger: 1 }, output: { itemId: 'braisedPrawn', qty: 1 } },
  // ── 批量场景B：海鲜剩余（第四批，清空 seafood）──
  { id: 'crayfishSpicy', name: '麻辣小龙虾', category: '主菜', reqLevel: 87, xp: 850, successChance: 0.66, ingredients: { fishing_ext_26: 3, chili: 3, garlic: 1 }, output: { itemId: 'crayfishSpicy', qty: 1 } },
  { id: 'catfishStew', name: '鲶鱼炖豆腐', category: '汤品', reqLevel: 90, xp: 930, successChance: 0.64, ingredients: { fishing_ext_27: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'catfishStew', qty: 1 } },
  { id: 'geoduckSteam', name: '清蒸象拔蚌', category: '主菜', reqLevel: 84, xp: 810, successChance: 0.67, ingredients: { fishing_ext2_25: 2, ginger: 1, soySauce: 1 }, output: { itemId: 'geoduckSteam', qty: 1 } },
  { id: 'scallopBroad', name: '蒜蓉带子', category: '主菜', reqLevel: 87, xp: 850, successChance: 0.66, ingredients: { fishing_ext2_26: 2, garlic: 2, saltOre: 1 }, output: { itemId: 'scallopBroad', qty: 1 } },
  { id: 'greenCrabSteam', name: '清蒸青蟹', category: '主菜', reqLevel: 90, xp: 930, successChance: 0.64, ingredients: { fishing_ext2_27: 2, ginger: 2, soySauce: 1 }, output: { itemId: 'greenCrabSteam', qty: 1 } },
  { id: 'blackFishSoup', name: '黑鱼汤', category: '汤品', reqLevel: 94, xp: 1020, successChance: 0.62, ingredients: { fishing_ext_28: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'blackFishSoup', qty: 1 } },
  { id: 'eelBraised', name: '红烧黄鳝', category: '主菜', reqLevel: 97, xp: 1120, successChance: 0.6, ingredients: { fishing_ext_29: 2, soySauce: 2, garlic: 1 }, output: { itemId: 'eelBraised', qty: 1 } },
  { id: 'loachSoup', name: '泥鳅豆腐汤', category: '汤品', reqLevel: 99, xp: 1200, successChance: 0.58, ingredients: { fishing_ext_30: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'loachSoup', qty: 1 } },
  { id: 'flowerCrabSteam', name: '清蒸花蟹', category: '主菜', reqLevel: 94, xp: 1020, successChance: 0.62, ingredients: { fishing_ext2_28: 2, ginger: 2, soySauce: 1 }, output: { itemId: 'flowerCrabSteam', qty: 1 } },
  { id: 'swimCrabStir', name: '梭子蟹炒年糕', category: '主菜', reqLevel: 97, xp: 1120, successChance: 0.6, ingredients: { fishing_ext2_29: 2, soySauce: 1, garlic: 1 }, output: { itemId: 'swimCrabStir', qty: 1 } },
  { id: 'jellyfishSalad', name: '凉拌海蜇', category: '主菜', reqLevel: 99, xp: 1200, successChance: 0.58, ingredients: { fishing_ext2_30: 2, garlic: 1, soySauce: 1 }, output: { itemId: 'jellyfishSalad', qty: 1 } },
  // ── 批量场景B：肉类 + 剩余蔬菜（清空 meat 与 vegetable）──
  { id: 'roastTurkey', name: '烤火鸡', category: '主菜', reqLevel: 97, xp: 1130, successChance: 0.6, ingredients: { hunting_ext_29: 2, soySauce: 1, garlic: 1 }, output: { itemId: 'roastTurkey', qty: 1 } },
  { id: 'ostrichSteak', name: '鸵鸟排', category: '主菜', reqLevel: 99, xp: 1200, successChance: 0.58, ingredients: { hunting_ext_30: 2, soySauce: 1, ginger: 1 }, output: { itemId: 'ostrichSteak', qty: 1 } },
  { id: 'porcupineBraised', name: '红烧箭猪', category: '主菜', reqLevel: 97, xp: 1130, successChance: 0.6, ingredients: { hunting_ext2_29: 2, soySauce: 2, ginger: 1 }, output: { itemId: 'porcupineBraised', qty: 1 } },
  { id: 'capybaraStew', name: '炖水豚', category: '汤品', reqLevel: 99, xp: 1200, successChance: 0.58, ingredients: { hunting_ext2_30: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'capybaraStew', qty: 1 } },
  { id: 'honeySugarcane', name: '蜜汁甘蔗', category: '主菜', reqLevel: 33, xp: 220, successChance: 0.83, ingredients: { foraging_ext2_10: 2, ginger: 1, saltOre: 1 }, output: { itemId: 'honeySugarcane', qty: 1 } },
  { id: 'broccoliGarlic', name: '蒜蓉西兰花', category: '主菜', reqLevel: 94, xp: 1020, successChance: 0.62, ingredients: { foraging_ext_28: 2, garlic: 2, saltOre: 1 }, output: { itemId: 'broccoliGarlic', qty: 1 } },
  { id: 'lettuceOyster', name: '蚝油生菜', category: '主菜', reqLevel: 97, xp: 1130, successChance: 0.6, ingredients: { foraging_ext_29: 2, soySauce: 2, garlic: 1 }, output: { itemId: 'lettuceOyster', qty: 1 } },
  { id: 'kohlrabiStir', name: '清炒苤蓝', category: '主菜', reqLevel: 99, xp: 1200, successChance: 0.58, ingredients: { foraging_ext_30: 2, garlic: 1, saltOre: 1 }, output: { itemId: 'kohlrabiStir', qty: 1 } },
  // ── 批量场景B：基础材料补齐（野牛肉→香煎野牛排）──
  { id: 'bisonSteak', name: '香煎野牛排', category: '主菜', reqLevel: 47, xp: 310, successChance: 0.79, ingredients: { bisonMeat: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'bisonSteak', qty: 1 } },
  { id: 'cookDown_1', name: '番茄酱拌面', category: '主菜', reqLevel: 30, xp: 360, successChance: 0.72, ingredients: { ketchup: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_1', qty: 1 } },
  { id: 'cookDown_2', name: '辣椒酱拌面', category: '主菜', reqLevel: 30, xp: 360, successChance: 0.72, ingredients: { hotSauce: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_2', qty: 1 } },
  { id: 'cookDown_3', name: '花椒油拌面', category: '主菜', reqLevel: 30, xp: 360, successChance: 0.72, ingredients: { peppercornOil: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_3', qty: 1 } },
  { id: 'cookDown_4', name: '松露酱拌面', category: '主菜', reqLevel: 31, xp: 372, successChance: 0.72, ingredients: { truffleSauce: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_4', qty: 1 } },
  { id: 'cookDown_5', name: '甜面酱拌面', category: '主菜', reqLevel: 31, xp: 372, successChance: 0.72, ingredients: { preserving_ext_03: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_5', qty: 1 } },
  { id: 'cookDown_6', name: '沙茶酱拌面', category: '主菜', reqLevel: 31, xp: 372, successChance: 0.72, ingredients: { preserving_ext_04: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_6', qty: 1 } },
  { id: 'cookDown_7', name: '花生酱拌面', category: '主菜', reqLevel: 31, xp: 372, successChance: 0.72, ingredients: { preserving_ext_05: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_7', qty: 1 } },
  { id: 'cookDown_8', name: '芝麻酱拌面', category: '主菜', reqLevel: 32, xp: 384, successChance: 0.72, ingredients: { preserving_ext_06: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_8', qty: 1 } },
  { id: 'cookDown_9', name: '蛋黄酱拌面', category: '主菜', reqLevel: 32, xp: 384, successChance: 0.72, ingredients: { preserving_ext_07: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_9', qty: 1 } },
  { id: 'cookDown_10', name: '芥末酱拌面', category: '主菜', reqLevel: 32, xp: 384, successChance: 0.72, ingredients: { preserving_ext_08: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_10', qty: 1 } },
  { id: 'cookDown_11', name: '黑胡椒酱拌面', category: '主菜', reqLevel: 32, xp: 384, successChance: 0.72, ingredients: { preserving_ext_09: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_11', qty: 1 } },
  { id: 'cookDown_12', name: '蘑菇酱拌面', category: '主菜', reqLevel: 33, xp: 396, successChance: 0.72, ingredients: { preserving_ext_10: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_12', qty: 1 } },
  { id: 'cookDown_13', name: '藤椒油拌面', category: '主菜', reqLevel: 33, xp: 396, successChance: 0.72, ingredients: { preserving_ext_11: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_13', qty: 1 } },
  { id: 'cookDown_14', name: '香醋拌面', category: '主菜', reqLevel: 33, xp: 396, successChance: 0.72, ingredients: { preserving_ext_12: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_14', qty: 1 } },
  { id: 'cookDown_15', name: '陈醋拌面', category: '主菜', reqLevel: 33, xp: 396, successChance: 0.72, ingredients: { preserving_ext_13: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_15', qty: 1 } },
  { id: 'cookDown_16', name: '苹果醋拌面', category: '主菜', reqLevel: 34, xp: 408, successChance: 0.72, ingredients: { preserving_ext_14: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_16', qty: 1 } },
  { id: 'cookDown_17', name: '泡椒拌面', category: '主菜', reqLevel: 34, xp: 408, successChance: 0.72, ingredients: { preserving_ext_15: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_17', qty: 1 } },
  { id: 'cookDown_18', name: '酱油膏拌面', category: '主菜', reqLevel: 34, xp: 408, successChance: 0.72, ingredients: { preserving_ext2_01: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_18', qty: 1 } },
  { id: 'cookDown_19', name: '老抽拌面', category: '主菜', reqLevel: 34, xp: 408, successChance: 0.72, ingredients: { preserving_ext2_02: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_19', qty: 1 } },
  { id: 'cookDown_20', name: '生抽拌面', category: '主菜', reqLevel: 35, xp: 420, successChance: 0.72, ingredients: { preserving_ext2_03: 2, flour: 2, saltOre: 1 }, output: { itemId: 'cookDown_20', qty: 1 } },
  { id: 'cookDown_21', name: '咸蛋煲仔饭', category: '主菜', reqLevel: 35, xp: 420, successChance: 0.72, ingredients: { preservedEgg: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_21', qty: 1 } },
  { id: 'cookDown_22', name: '酸豆角煲仔饭', category: '主菜', reqLevel: 35, xp: 420, successChance: 0.72, ingredients: { preserving_ext_16: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_22', qty: 1 } },
  { id: 'cookDown_23', name: '萝卜干煲仔饭', category: '主菜', reqLevel: 35, xp: 420, successChance: 0.72, ingredients: { preserving_ext_18: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_23', qty: 1 } },
  { id: 'cookDown_24', name: '榨菜煲仔饭', category: '主菜', reqLevel: 36, xp: 432, successChance: 0.72, ingredients: { preserving_ext_19: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_24', qty: 1 } },
  { id: 'cookDown_25', name: '雪菜煲仔饭', category: '主菜', reqLevel: 36, xp: 432, successChance: 0.72, ingredients: { preserving_ext_20: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_25', qty: 1 } },
  { id: 'cookDown_26', name: '咸鱼煲仔饭', category: '主菜', reqLevel: 36, xp: 432, successChance: 0.72, ingredients: { preserving_ext_21: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_26', qty: 1 } },
  { id: 'cookDown_27', name: '鱼干煲仔饭', category: '主菜', reqLevel: 36, xp: 432, successChance: 0.72, ingredients: { preserving_ext_22: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_27', qty: 1 } },
  { id: 'cookDown_28', name: '虾酱煲仔饭', category: '主菜', reqLevel: 37, xp: 444, successChance: 0.72, ingredients: { preserving_ext_23: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_28', qty: 1 } },
  { id: 'cookDown_29', name: '蟹酱煲仔饭', category: '主菜', reqLevel: 37, xp: 444, successChance: 0.72, ingredients: { preserving_ext_24: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_29', qty: 1 } },
  { id: 'cookDown_30', name: '蚝油煲仔饭', category: '主菜', reqLevel: 37, xp: 444, successChance: 0.72, ingredients: { preserving_ext_25: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_30', qty: 1 } },
  { id: 'cookDown_31', name: '橄榄菜煲仔饭', category: '主菜', reqLevel: 37, xp: 444, successChance: 0.72, ingredients: { preserving_ext_26: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_31', qty: 1 } },
  { id: 'cookDown_32', name: '酸梅煲仔饭', category: '主菜', reqLevel: 38, xp: 456, successChance: 0.72, ingredients: { preserving_ext_27: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_32', qty: 1 } },
  { id: 'cookDown_33', name: '酱黄瓜煲仔饭', category: '主菜', reqLevel: 38, xp: 456, successChance: 0.72, ingredients: { preserving_ext_28: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_33', qty: 1 } },
  { id: 'cookDown_34', name: '卤蛋煲仔饭', category: '主菜', reqLevel: 38, xp: 456, successChance: 0.72, ingredients: { preserving_ext_29: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_34', qty: 1 } },
  { id: 'cookDown_35', name: '咸柠檬煲仔饭', category: '主菜', reqLevel: 38, xp: 456, successChance: 0.72, ingredients: { preserving_ext_30: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_35', qty: 1 } },
  { id: 'cookDown_36', name: '腊肠煲仔饭', category: '主菜', reqLevel: 39, xp: 468, successChance: 0.72, ingredients: { preserving_ext2_24: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_36', qty: 1 } },
  { id: 'cookDown_37', name: '酱鸭煲仔饭', category: '主菜', reqLevel: 39, xp: 468, successChance: 0.72, ingredients: { preserving_ext2_26: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_37', qty: 1 } },
  { id: 'cookDown_38', name: '酱肘子煲仔饭', category: '主菜', reqLevel: 39, xp: 468, successChance: 0.72, ingredients: { preserving_ext2_27: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_38', qty: 1 } },
  { id: 'cookDown_39', name: '酱牛肉煲仔饭', category: '主菜', reqLevel: 39, xp: 468, successChance: 0.72, ingredients: { preserving_ext2_28: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_39', qty: 1 } },
  { id: 'cookDown_40', name: '咸鸭蛋煲仔饭', category: '主菜', reqLevel: 40, xp: 480, successChance: 0.72, ingredients: { preserving_ext2_29: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_40', qty: 1 } },
  { id: 'cookDown_41', name: '皮蛋煲仔饭', category: '主菜', reqLevel: 40, xp: 480, successChance: 0.72, ingredients: { preserving_ext2_30: 2, rice: 2, saltOre: 1 }, output: { itemId: 'cookDown_41', qty: 1 } },
  { id: 'wildDish_1', name: '红烧麻雀', category: '主菜', reqLevel: 1, xp: 10, successChance: 0.7, ingredients: { hunting_ext_01: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_1', qty: 1 } },
  { id: 'wildDish_2', name: '香煎鹌鹑', category: '主菜', reqLevel: 4, xp: 40, successChance: 0.7, ingredients: { hunting_ext_02: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_2', qty: 1 } },
  { id: 'wildDish_3', name: '干煸鸽子', category: '主菜', reqLevel: 7, xp: 70, successChance: 0.7, ingredients: { hunting_ext_03: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_3', qty: 1 } },
  { id: 'wildDish_4', name: '碳烤斑鸠', category: '主菜', reqLevel: 11, xp: 110, successChance: 0.7, ingredients: { hunting_ext_04: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_4', qty: 1 } },
  { id: 'wildDish_5', name: '椒盐大雁', category: '主菜', reqLevel: 17, xp: 170, successChance: 0.7, ingredients: { hunting_ext_06: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_5', qty: 1 } },
  { id: 'wildDish_6', name: '卤煮獾肉', category: '主菜', reqLevel: 21, xp: 210, successChance: 0.7, ingredients: { hunting_ext_07: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_6', qty: 1 } },
  { id: 'wildDish_7', name: '酱爆果子狸', category: '主菜', reqLevel: 24, xp: 240, successChance: 0.7, ingredients: { hunting_ext_08: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_7', qty: 1 } },
  { id: 'wildDish_8', name: '葱爆豪猪', category: '主菜', reqLevel: 28, xp: 280, successChance: 0.7, ingredients: { hunting_ext_09: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_8', qty: 1 } },
  { id: 'wildDish_9', name: '孜然羚羊', category: '主菜', reqLevel: 31, xp: 310, successChance: 0.7, ingredients: { hunting_ext_10: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_9', qty: 1 } },
  { id: 'wildDish_10', name: '砂锅岩羊', category: '主菜', reqLevel: 34, xp: 340, successChance: 0.7, ingredients: { hunting_ext_11: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_10', qty: 1 } },
  { id: 'wildDish_11', name: '藤椒盘羊', category: '主菜', reqLevel: 38, xp: 380, successChance: 0.7, ingredients: { hunting_ext_12: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_11', qty: 1 } },
  { id: 'wildDish_12', name: '葱烧麂子', category: '主菜', reqLevel: 41, xp: 410, successChance: 0.7, ingredients: { hunting_ext_13: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_12', qty: 1 } },
  { id: 'wildDish_13', name: '红烧狍子', category: '主菜', reqLevel: 44, xp: 440, successChance: 0.7, ingredients: { hunting_ext_14: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_13', qty: 1 } },
  { id: 'wildDish_14', name: '香煎驼鹿', category: '主菜', reqLevel: 48, xp: 480, successChance: 0.7, ingredients: { hunting_ext_15: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_14', qty: 1 } },
  { id: 'wildDish_15', name: '干煸驯鹿', category: '主菜', reqLevel: 51, xp: 510, successChance: 0.7, ingredients: { hunting_ext_16: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_15', qty: 1 } },
  { id: 'wildDish_16', name: '碳烤野驴', category: '主菜', reqLevel: 55, xp: 550, successChance: 0.7, ingredients: { hunting_ext_17: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_16', qty: 1 } },
  { id: 'wildDish_17', name: '椒盐刺猬', category: '主菜', reqLevel: 58, xp: 580, successChance: 0.7, ingredients: { hunting_ext_18: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_17', qty: 1 } },
  { id: 'wildDish_18', name: '卤煮蛇肉', category: '主菜', reqLevel: 61, xp: 610, successChance: 0.7, ingredients: { hunting_ext_19: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_18', qty: 1 } },
  { id: 'wildDish_19', name: '酱爆蜥蜴', category: '主菜', reqLevel: 65, xp: 650, successChance: 0.7, ingredients: { hunting_ext_20: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_19', qty: 1 } },
  { id: 'wildDish_20', name: '葱爆田鸡', category: '主菜', reqLevel: 68, xp: 680, successChance: 0.7, ingredients: { hunting_ext_21: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_20', qty: 1 } },
  { id: 'wildDish_21', name: '孜然牛蛙', category: '主菜', reqLevel: 71, xp: 710, successChance: 0.7, ingredients: { hunting_ext_22: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_21', qty: 1 } },
  { id: 'wildDish_22', name: '砂锅竹鼠', category: '主菜', reqLevel: 75, xp: 750, successChance: 0.7, ingredients: { hunting_ext_23: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_22', qty: 1 } },
  { id: 'wildDish_23', name: '藤椒旱獭', category: '主菜', reqLevel: 78, xp: 780, successChance: 0.7, ingredients: { hunting_ext_24: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_23', qty: 1 } },
  { id: 'wildDish_24', name: '葱烧河狸', category: '主菜', reqLevel: 82, xp: 820, successChance: 0.7, ingredients: { hunting_ext_25: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_24', qty: 1 } },
  { id: 'wildDish_25', name: '红烧水獭', category: '主菜', reqLevel: 85, xp: 850, successChance: 0.7, ingredients: { hunting_ext_26: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_25', qty: 1 } },
  { id: 'wildDish_26', name: '香煎香猪', category: '主菜', reqLevel: 88, xp: 880, successChance: 0.7, ingredients: { hunting_ext_27: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_26', qty: 1 } },
  { id: 'wildDish_27', name: '干煸竹鸡', category: '主菜', reqLevel: 92, xp: 920, successChance: 0.7, ingredients: { hunting_ext_28: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_27', qty: 1 } },
  { id: 'wildDish_28', name: '碳烤獐子', category: '主菜', reqLevel: 1, xp: 10, successChance: 0.7, ingredients: { hunting_ext2_01: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_28', qty: 1 } },
  { id: 'wildDish_29', name: '椒盐麋鹿', category: '主菜', reqLevel: 4, xp: 40, successChance: 0.7, ingredients: { hunting_ext2_02: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_29', qty: 1 } },
  { id: 'wildDish_30', name: '卤煮黄羊', category: '主菜', reqLevel: 7, xp: 70, successChance: 0.7, ingredients: { hunting_ext2_03: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_30', qty: 1 } },
  { id: 'wildDish_31', name: '酱爆青羊', category: '主菜', reqLevel: 11, xp: 110, successChance: 0.7, ingredients: { hunting_ext2_04: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_31', qty: 1 } },
  { id: 'wildDish_32', name: '葱爆岩貂', category: '主菜', reqLevel: 14, xp: 140, successChance: 0.7, ingredients: { hunting_ext2_05: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_32', qty: 1 } },
  { id: 'wildDish_33', name: '孜然紫貂', category: '主菜', reqLevel: 17, xp: 170, successChance: 0.7, ingredients: { hunting_ext2_06: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_33', qty: 1 } },
  { id: 'wildDish_34', name: '砂锅雪貂', category: '主菜', reqLevel: 21, xp: 210, successChance: 0.7, ingredients: { hunting_ext2_07: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_34', qty: 1 } },
  { id: 'wildDish_35', name: '藤椒松鼠', category: '主菜', reqLevel: 24, xp: 240, successChance: 0.7, ingredients: { hunting_ext2_08: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_35', qty: 1 } },
  { id: 'wildDish_36', name: '葱烧飞鼠', category: '主菜', reqLevel: 28, xp: 280, successChance: 0.7, ingredients: { hunting_ext2_09: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_36', qty: 1 } },
  { id: 'wildDish_37', name: '红烧蜜獾', category: '主菜', reqLevel: 31, xp: 310, successChance: 0.7, ingredients: { hunting_ext2_10: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_37', qty: 1 } },
  { id: 'wildDish_38', name: '香煎狼獾', category: '主菜', reqLevel: 34, xp: 340, successChance: 0.7, ingredients: { hunting_ext2_11: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_38', qty: 1 } },
  { id: 'wildDish_39', name: '干煸猞猁', category: '主菜', reqLevel: 38, xp: 380, successChance: 0.7, ingredients: { hunting_ext2_12: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_39', qty: 1 } },
  { id: 'wildDish_40', name: '碳烤豹猫', category: '主菜', reqLevel: 41, xp: 410, successChance: 0.7, ingredients: { hunting_ext2_13: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_40', qty: 1 } },
  { id: 'wildDish_41', name: '椒盐田鼠', category: '主菜', reqLevel: 44, xp: 440, successChance: 0.7, ingredients: { hunting_ext2_14: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_41', qty: 1 } },
  { id: 'wildDish_42', name: '卤煮鼬', category: '主菜', reqLevel: 48, xp: 480, successChance: 0.7, ingredients: { hunting_ext2_15: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_42', qty: 1 } },
  { id: 'wildDish_43', name: '酱爆鼢鼠', category: '主菜', reqLevel: 51, xp: 510, successChance: 0.7, ingredients: { hunting_ext2_16: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_43', qty: 1 } },
  { id: 'wildDish_44', name: '葱爆竹蜂', category: '主菜', reqLevel: 55, xp: 550, successChance: 0.7, ingredients: { hunting_ext2_17: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_44', qty: 1 } },
  { id: 'wildDish_45', name: '孜然蝗虫', category: '主菜', reqLevel: 58, xp: 580, successChance: 0.7, ingredients: { hunting_ext2_18: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_45', qty: 1 } },
  { id: 'wildDish_46', name: '砂锅蝉', category: '主菜', reqLevel: 61, xp: 610, successChance: 0.7, ingredients: { hunting_ext2_19: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_46', qty: 1 } },
  { id: 'wildDish_47', name: '藤椒蝎子', category: '主菜', reqLevel: 65, xp: 650, successChance: 0.7, ingredients: { hunting_ext2_20: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_47', qty: 1 } },
  { id: 'wildDish_48', name: '葱烧鹧鸪', category: '主菜', reqLevel: 68, xp: 680, successChance: 0.7, ingredients: { hunting_ext2_21: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_48', qty: 1 } },
  { id: 'wildDish_49', name: '红烧白鹇', category: '主菜', reqLevel: 71, xp: 710, successChance: 0.7, ingredients: { hunting_ext2_22: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_49', qty: 1 } },
  { id: 'wildDish_50', name: '香煎锦鸡', category: '主菜', reqLevel: 75, xp: 750, successChance: 0.7, ingredients: { hunting_ext2_23: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_50', qty: 1 } },
  { id: 'wildDish_51', name: '干煸孔雀', category: '主菜', reqLevel: 78, xp: 780, successChance: 0.7, ingredients: { hunting_ext2_24: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_51', qty: 1 } },
  { id: 'wildDish_52', name: '碳烤鸸鹋', category: '主菜', reqLevel: 82, xp: 820, successChance: 0.7, ingredients: { hunting_ext2_25: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_52', qty: 1 } },
  { id: 'wildDish_53', name: '椒盐斑马', category: '主菜', reqLevel: 85, xp: 850, successChance: 0.7, ingredients: { hunting_ext2_26: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_53', qty: 1 } },
  { id: 'wildDish_54', name: '卤煮角马', category: '主菜', reqLevel: 88, xp: 880, successChance: 0.7, ingredients: { hunting_ext2_27: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_54', qty: 1 } },
  { id: 'wildDish_55', name: '酱爆食蚁兽', category: '主菜', reqLevel: 92, xp: 920, successChance: 0.7, ingredients: { hunting_ext2_28: 2, saltOre: 1, soySauce: 1 }, output: { itemId: 'wildDish_55', qty: 1 } },
  { id: 'wildDish_551', name: '清炒沙丁鱼', category: '主菜', reqLevel: 1, xp: 12, successChance: 0.8, ingredients: { fishing_ext_01: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'wildDish_551', qty: 1 } },
  { id: 'wildDish_552', name: '清炒鲱鱼', category: '主菜', reqLevel: 4, xp: 48, successChance: 0.8, ingredients: { fishing_ext_02: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'wildDish_552', qty: 1 } },
  { id: 'wildDish_553', name: '清炒鲷鱼', category: '主菜', reqLevel: 1, xp: 12, successChance: 0.8, ingredients: { fishing_ext2_01: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'wildDish_553', qty: 1 } },
  { id: 'wildDish_554', name: '清炒河豚', category: '主菜', reqLevel: 4, xp: 48, successChance: 0.8, ingredients: { fishing_ext2_02: 2, saltOre: 1, ginger: 1 }, output: { itemId: 'wildDish_554', qty: 1 } },
  { id: 'wildDish_555', name: '清炒芜菁', category: '主菜', reqLevel: 7, xp: 84, successChance: 0.8, ingredients: { excavation_ext_03: 2, saltOre: 1, garlic: 1 }, output: { itemId: 'wildDish_555', qty: 1 } },
  { id: 'wildDish_556', name: '清炒菱角', category: '主菜', reqLevel: 24, xp: 288, successChance: 0.8, ingredients: { excavation_ext_08: 2, saltOre: 1, garlic: 1 }, output: { itemId: 'wildDish_556', qty: 1 } },
]

export class CookingSkill extends ProductionSkill {
  constructor(player) {
    super('cooking', player, raiseRecipeLevels([...COOKING_RECIPES, ...PRODUCTION_EXT.cooking, ...PRODUCTION_EXT2.cooking]))
  }
}
